### ISSUE TITLE
change parent repository

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/git-rstudio-basics#20]
When making a PR, it automatically redirects to the parent repository. It is possible to change the recipient of the PR?

![image](https://github.com/epiverse-trace/git-rstudio-basics/assets/21230390/f42fc45e-aae9-4308-be36-6408391c75fa)

_Derived from a post by @avallecam in https://github.com/epiverse-trace/git-rstudio-basics/issues/1#issuecomment-1783152562_

**Comment by avallecam** [comment]
@Bisaloo did you have this situation while making your latest PR in this repo?

**Comment by Bisaloo** [comment]
Unfortunately, that normal GitHub behaviour. When opening a PR from a fork, it will by default target the parent repo. There is a feature request to make this a setting but nothing has happened on that front yet: https://github.com/orgs/community/discussions/11729.

**Comment by avallecam** [comment]
Thank you for the reference! I thought I needed to do some complex git locally, but know I know I can leave with it 👍
